### login - Admin
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "cpf": "11111111111",
  "senha": "Admin123"
}

### login
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "cpf": "22222222222",
  "senha": "fiscal"
}

### login
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "cpf": "33333333333",
  "senha": "Administrativo@3"
}


### resetOtherUserPassword
PUT http://localhost:3000/auth/resetAny
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibm9tZSI6IkFkbWluIENoZWZlIiwidGlwbyI6IkFkbWluIiwiaWF0IjoxNzY0MjQxNzk3LCJleHAiOjE3NjQyNTYxOTd9.5_Z93AE40IlpKXGzL_oSEB8p10ScwHY9xnuh0Hpg3U0

{
  "id": 2,
  "senhaAdm": "admin",
  "novaSenha": "fiscal"
}

### DeleteUser
DELETE http://localhost:3000/auth/delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibm9tZSI6IkFkbWluIENoZWZlIiwidGlwbyI6IkFkbWluIiwiaWF0IjoxNzY0MjQxNzk3LCJleHAiOjE3NjQyNTYxOTd9.5_Z93AE40IlpKXGzL_oSEB8p10ScwHY9xnuh0Hpg3U0

{
  "id": 86
}

### All users
GET http://localhost:3000/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibm9tZSI6IkFkbWluIENoZWZlIiwidGlwbyI6IkFkbWluIiwiaWF0IjoxNzY0MzYwODQwLCJleHAiOjE3NjQzNzUyNDB9.WSd04CbtSjwdj4ibAA-XAanQe1Urj4SlQ2QPC--R0tA

### Signup
POST http://localhost:3000/auth/signup
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibm9tZSI6IkFkbWluIENoZWZlIiwidGlwbyI6IkFkbWluIiwiaWF0IjoxNzY0MjQyNTA0LCJleHAiOjE3NjQyNTY5MDR9.M56RdLAFFHzCr8ixXgyGs5VdlaWX8A3HVEWKdi0aQOI

{
  "cpf": "33333333333",
  "senha": "Administrativo@3",
  "nome": "Fiscal Administrativo",
  "tipo": "Administrativo"
}

### Update own password
PUT http://localhost:3000/auth/updatePassword
Content-Type: application/json
Authorization: Bearer

{
  "id": 3,
  "senhaAntiga": "Administrativo@4",
  "novaSenha": "fiscal",
  "confirmaSenha": "fiscal"
}

### relatórios n processados
GET http://localhost:3000/relatorios-diarios/nao-processados
Authorization: Bearer 


### explos de caso
GET http://localhost:3000/autoinfracao/exemploCaso
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwibm9tZSI6IkZpc2NhbCBkZSBDYW1wbyIsInRpcG8iOiJDYW1wbyIsImlhdCI6MTc2NDM3MTg0OCwiZXhwIjoxNzY0Mzg2MjQ4fQ.VeBw9Rga1cHUh4tQ2YsPdOOXT2-1cJ89vnQaaZXFCXg

### All users
GET http://localhost:3000/relatorios-diarios/export/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwibm9tZSI6IkZpc2NhbCBkZSBDYW1wbyIsInRpcG8iOiJDYW1wbyIsImlhdCI6MTc2NDM3MjA3NSwiZXhwIjoxNzY0Mzg2NDc1fQ.W6IdueLKPeV6GtWK0kOTTU5BPh2OIIY5EGpAMVlF3v0